name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npx hardhat test
      env:
        # These are not needed for the tests but
        # hardhat fails to start if not present.
        NODE_TEST: "x"
        NODE_MAIN: "x"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
